import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import * as Popper from "@popperjs/core"
import { Routes, Route } from 'react-router-dom';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const jejuMyeongjo = localFont({
  src: "./fonts/JejuMyeongjo-Regular.woff",
  variable: "--font-jejuMyeongjo-regular",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//Create a header for the page
const Header = () => {
  return (
    <div className="container">
    <header className="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <div className="col-md-3 mb-2 mb-md-0">
        <a href="/" className="d-inline-flex link-body-emphasis text-decoration-none">
          <div className="d-flex align-items-center">
            <svg className="bi" width="40" height="32" role="img" aria-label="Bootstrap">
              <use href="#bootstrap"></use>
            </svg>
            <span className="ms-2">Tables<b>4u</b></span>
          </div>
        </a>
      </div>

      <ul className="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="/home" className="nav-link px-2">Home</a></li>
        <li><a href="/consumerActive" className="nav-link px-2">Consumer</a></li>
        <li><a href="/findReservation" className="nav-link px-2">Find Reservation</a></li>
      </ul>

      <div className="col-md-3 text-end">
        <a href="/login" type="button" className="btn btn-outline-primary me-2">Login</a>
        <a href="/createRestaurant" type="button" className="btn btn-primary">Register your restaurant</a>
      </div>
    </header>
  </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jejuMyeongjo.variable} antialiased`} >
        {Header()}
        {children}
      </body>
    </html>
  );
}
